select
identifikator_korisnika, ime_korisnika, prezime_korisnika,
korisnicko_ime_korisnika, hash_sifre_korisnika, tip_korisnika,
adresa_korisnika,telefon_korisnika,radno_mjesto_korisnika,
elpostakorisnika, vebsajtovikorisnika, salt_sifre_korisnika
from bk_programiranje_data;