/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programiranje.podaci_korisnika.standard;

/**
 * Protokol PROPIS - naredbe
 * @author Mikec
 */
public enum NaredbeProtokolaPROPIS {
    PROPIS_ZAHTIJEV_ZA_VLASTITIM_SERTIFIKATOM, 
    PROPIS_ZAHTIJEV_ZA_VLASTITIM_PODACIMA,
    PROPIS_ZAHTIJEV_ZA_KORISNICKIM_PODACIMA, 
    PROPIS_ZAHTIJEV_ZA_KORISNICKIM_SERTIFIKATOM,
    PROPIS_ZAHTIJEV_ZA_PORUKOM_U_SLICI,
    PROPIS_INFORMACIJA_O_VLASTITOM_SERTIFIKATU, 
    PROPIS_INFORMACIJA_O_BROJU_KORISNIIKA,
    PROPIS_INFORMACIJA_O_BROJU_SERTIFIKATA,
    PROPIS_INFORMACIJA_O_BROJU_SLIKA_S_PORUKAMA,
    PROPIS_INFORMACIJA_O_BROJU_SLIKA_S_PORUKAMA_ZA_KORISNIKA,
    PROPIS_LISTANJE_KORISNICKIH_IMENA,
    PROPIS_LISTANJE_KORISNICKIH_IMENA_SERTIFIKOVANIH_KORISNIKA,
    PROPIS_LISTANJE_SERTIFIKATA_KORISNIKA, 
    PROPIS_LISTANJE_IMENA_SLIKA_SA_PORUKAMA,
    PROPIS_LISTANJE_IMENA_SLIKA_SA_PORUKAMA_ZA_KORISNIKA, 
    PROPIS_POSTAVLJANJE_PORUKE_U_SLICI,
    PROPIS_PREUZIMANJE_CILJNE_SLIKE_S_PORUKOM,
    PROPIS_PREUZIMANJE_SVIH_SLIKA_S_PORUKAMA_SA_LISTE, 
    PROPIS_PREUZIMANJE_SVIH_SLIKA_S_PORUKAMA_ZA_KORISNIKA,
    PROPIS_LISANJE_PODATAKA_ZA_KORISNIKE_IZ_LISTE,
    PROPIS_ZAHTIJEV_ZA_SPISKOM_ISPORUKA,
    PROPIS_ZAHTIJEV_ZA_POVLACENJEM_SERTIFIKATA, 
    PROPIS_ZAHTIJEV_ZA_CRL_LISTOM, 
}
